# CodeRabbit Configuration File
# For more information, visit https://docs.coderabbit.ai/getting-started/configure-coderabbit/

language: "en-US"
reviews:
  profile: "chill" # Options: chill, assertive, obsessive
  request_review_command: "review"
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!node_modules/**"
    - "!.next/**"
    - "!dist/**"
    - "!build/**"
    - "!package-lock.json"
    - "!yarn.lock"
    - "!*.min.js"
    - "!*.map"
chat:
  enabled: true
